import type { ServicePageContent } from "./service-page-types";

function diagnosticHref(subject: string, prompt: string) {
  const body = [
    "Company:",
    "Website:",
    "Your role:",
    prompt,
  ].join("\n");

  return `mailto:hello@growandclose.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
}

export const positioningAndMessaging: ServicePageContent = {
  number: "01",
  slug: "positioning-and-messaging",
  name: "Positioning & messaging",
  systemName: "Market Signal System",
  circuitVariant: "market",
  metaTitle: "Positioning & Messaging System | Grow & Close",
  metaDescription:
    "Turn market evidence, customer language, product truth, and commercial choices into a message system that gets sharper as buyers respond.",
  heroLead: "Make your market understand",
  heroAccent: "why you, now.",
  heroLede:
    "We turn founder context, customer language, competitor patterns, product truth, and sales friction into a message architecture your whole GTM motion can use and improve.",
  diagnosticName: "Message Gap Map",
  ctaLabel: "Get the message map",
  diagnosticHref: diagnosticHref(
    "Message Gap Map",
    "Where does your current story lose buyers?:",
  ),
  outcomes: ["Sharper category frame", "One commercial story", "Proof behind claims", "Signals that update it"],
  problemHeading: "Your message is not unclear because the words need polishing.",
  problemLede:
    "The visible symptom is copy drift. The deeper problem is that market evidence, product choices, customer language, and sales learning never meet in one governed decision system.",
  problems: [
    {
      title: "Every team tells a different story.",
      copy: "Founders lead with vision, product leads with features, marketing leads with benefits, and sales rewrites the pitch around the last objection.",
    },
    {
      title: "Category language makes you disappear.",
      copy: "The homepage sounds accurate but interchangeable. Buyers recognise the category, then struggle to see why this company deserves the next click or call.",
    },
    {
      title: "Claims outrun evidence.",
      copy: "Big promises reach the page before proof, caveats, or a believable mechanism. Internal confidence rises while buyer trust falls.",
    },
    {
      title: "Launches reset the argument.",
      copy: "Each campaign, page, and deck starts a fresh messaging debate because no one records what was chosen, rejected, tested, or learned.",
    },
  ],
  symptom: "Copy changes every cycle",
  rootCause: "No governed link between market evidence, commercial choices, and buyer response",
  circuitHeading: "Touch the market signal. See which message decision it changes.",
  circuitLede:
    "Positioning becomes useful when evidence can challenge the story, decisions stay explicit, and every customer-facing surface inherits the same commercial spine.",
  stages: [
    {
      label: "Observe",
      title: "Collect the language buyers already use.",
      copy: "Customer calls, lost deals, support threads, search behaviour, competitor claims, founder beliefs, and product trade-offs enter one evidence base.",
      input: "MARKET + CUSTOMER EVIDENCE",
      output: "LANGUAGE BANK + TENSION MAP",
      checkpoint: "Is this repeated evidence or one loud opinion?",
    },
    {
      label: "Diagnose",
      title: "Find the decision hiding beneath the copy problem.",
      copy: "We separate category confusion, weak differentiation, audience mismatch, proof gaps, and message-order problems before writing a line.",
      input: "EVIDENCE BASE",
      output: "MESSAGE GAP DIAGNOSIS",
      checkpoint: "Can we name the expensive misunderstanding?",
    },
    {
      label: "Choose",
      title: "Commit to a frame the company can defend.",
      copy: "Audience, category, alternative, differentiated value, reason to believe, and commercial urgency become explicit choices with stated exclusions.",
      input: "DIAGNOSIS + STRATEGY",
      output: "POSITIONING DECISIONS",
      checkpoint: "What are we willing not to claim?",
    },
    {
      label: "Deploy",
      title: "Turn one position into a usable message system.",
      copy: "The core argument becomes homepage language, campaign hooks, sales talk tracks, proof modules, objections, and channel-ready message variants.",
      input: "POSITIONING DECISIONS",
      output: "MESSAGE ARCHITECTURE",
      checkpoint: "Does every surface preserve the same commercial logic?",
    },
    {
      label: "Learn",
      title: "Let buyer response sharpen the next version.",
      copy: "Page behaviour, sales calls, replies, win-loss notes, and campaign signals update the evidence bank without letting one metric rewrite the strategy.",
      input: "BUYER RESPONSE",
      output: "VERSIONED MESSAGE STATE",
      checkpoint: "What changed: comprehension, belief, or action?",
    },
  ],
  returnLabel: "BUYER RESPONSE RE-ENTERS THE EVIDENCE BASE",
  assetHeading: "The deliverable is not a tagline. It is shared commercial state.",
  assetLede:
    "The message should survive a new page, new rep, new campaign, and new quarter without forcing the company to rediscover its own argument.",
  assets: [
    { label: "FRAME", title: "Positioning decision record", copy: "Audience, alternative, differentiated value, category choice, urgency, exclusions, and reasons behind each decision." },
    { label: "SYSTEM", title: "Message architecture", copy: "Core narrative, claim hierarchy, proof modules, objection paths, channel variants, and language rules." },
    { label: "MEMORY", title: "Market evidence ledger", copy: "Customer language, sales friction, test results, rejected claims, open questions, and version history." },
  ],
  packageHeading: "Install the message system before rewriting every asset.",
  packageLede:
    "A typical first month resolves the commercial argument, deploys it on one high-value surface, then creates a learning path for the next decision.",
  phases: [
    { period: "DAYS 01-07", title: "Gather the market evidence", copy: "Interview key stakeholders, review customer and sales material, map competitors, audit current claims, and isolate message drift.", deliverables: "Evidence bank · competitor pattern map · message-gap diagnosis" },
    { period: "DAYS 08-14", title: "Make the hard choices", copy: "Run the positioning working session. Choose the audience, alternative, frame, differentiated value, proof standard, and claims to retire.", deliverables: "Positioning record · claim hierarchy · exclusions" },
    { period: "DAYS 15-21", title: "Build the architecture", copy: "Turn decisions into a usable narrative, message pillars, proof modules, objections, talk tracks, and channel variations.", deliverables: "Message architecture · proof bank · talk track" },
    { period: "DAYS 22-30", title: "Deploy and instrument", copy: "Apply the system to one priority surface and define the buyer and sales signals that will govern the next revision.", deliverables: "One live-ready application · signal plan · version ledger" },
  ],
  studioOwns: ["Research design and evidence synthesis", "Positioning facilitation and decision record", "Message architecture and proof hierarchy", "One priority application", "Signal plan and version governance"],
  customerOwns: ["Founder and GTM stakeholder access", "Customer, product, and deal context", "Commercial choices and final approval", "Legal review for regulated claims", "Access to live buyer and sales feedback"],
  diagnosticHeading: "Find where your story loses meaning, belief, or urgency.",
  diagnosticCopy:
    "We review your homepage, sales story, competitor frame, customer language, and proof. You get a one-page map of the contradictions, missing decisions, and first message problem worth fixing.",
  diagnosticIncludes: ["Category and audience drift", "Claim-to-proof gaps", "Message-order friction", "Cross-channel contradictions", "First decision to resolve"],
  faqs: [
    { question: "Is this a brand workshop?", answer: "No. This is a commercial positioning and message system tied to buyer comprehension, sales conversations, proof, and live GTM surfaces. Visual identity can inherit the decisions, but it is not the primary output." },
    { question: "Do you need customer research?", answer: "Usually. Existing interviews, call recordings, win-loss notes, support threads, and sales context may be enough to start. If the evidence is thin, we design a focused research pass before making confident claims." },
    { question: "Will you rewrite the whole website?", answer: "Not by default. We first resolve the shared argument, then apply it to the surface with the highest commercial leverage. A broader page rebuild can become the next owned motion." },
    { question: "How do we know the positioning works?", answer: "No single conversion rate proves positioning. We combine comprehension, sales adoption, objection patterns, qualified response, and downstream action. Strategy remains stable until evidence shows which assumption failed." },
  ],
  closingKicker: "STOP REWRITING A STORY YOU HAVE NOT DECIDED",
  closingHeading: "Build the message system your next motion can inherit.",
};

export const landingPages: ServicePageContent = {
  number: "02",
  slug: "landing-pages",
  name: "Landing pages",
  systemName: "Page Learning System",
  circuitVariant: "argument",
  metaTitle: "Landing Page System | Grow & Close",
  metaDescription: "Turn traffic intent, one sharp argument, proof, and behavioural signals into landing pages that learn instead of becoming static campaign assets.",
  heroLead: "Turn one sharp argument",
  heroAccent: "into qualified action.",
  heroLede: "We connect traffic intent, message, proof, interaction, build quality, and measurement so your landing page does more than look finished. It explains, qualifies, converts, and teaches the next version.",
  diagnosticName: "Page Argument Map",
  ctaLabel: "Get the page map",
  diagnosticHref: diagnosticHref("Page Argument Map", "Which page or campaign needs to convert better?:"),
  outcomes: ["Intent-message match", "One argument spine", "Proof in the right order", "A page that learns"],
  problemHeading: "Most landing pages are assembled before the argument is decided.",
  problemLede: "Copy, design, forms, and analytics arrive as separate workstreams. The page ships, but nobody can explain which belief it had to change or what the next signal should teach.",
  problems: [
    { title: "Traffic and page tell different stories.", copy: "The ad promises one outcome, the headline broadens it, and the form asks for commitment before the visitor sees relevant proof." },
    { title: "Sections replace reasoning.", copy: "A hero, logo bar, feature grid, and FAQ appear because templates expect them, not because the buyer's decision needs them." },
    { title: "Proof arrives too late or says too little.", copy: "Testimonials, data, product evidence, and risk reversal sit in decorative blocks instead of answering the objection created one section earlier." },
    { title: "The page ships without a learning contract.", copy: "Events are tracked, but no one defines what each signal means, when to intervene, or which change is safe to test." },
  ],
  symptom: "Traffic arrives but qualified action stays weak",
  rootCause: "No shared argument connecting visitor intent, proof sequence, interaction, and measurement",
  circuitHeading: "Select a page layer. See the decision it must earn.",
  circuitLede: "A high-converting page is a sequenced argument. Each layer earns permission for the next, while behavioural evidence shows where comprehension or belief breaks.",
  stages: [
    { label: "Intent", title: "Name why this visitor arrived now.", copy: "We map source, awareness, job, urgency, objections, and expected next step before choosing a headline or layout.", input: "TRAFFIC + AUDIENCE CONTEXT", output: "INTENT CONTRACT", checkpoint: "Would this visitor recognise their exact situation?" },
    { label: "Argument", title: "Build the shortest believable path to action.", copy: "Problem, mechanism, differentiated value, proof, objections, and CTA become one ordered reasoning spine, not a stack of interchangeable sections.", input: "INTENT + MESSAGE SYSTEM", output: "PAGE ARGUMENT", checkpoint: "What must the visitor believe before the CTA feels rational?" },
    { label: "Evidence", title: "Place proof where doubt appears.", copy: "Customer evidence, product detail, process transparency, data, and boundaries answer specific doubts at the moment they surface.", input: "OBJECTION MAP + PROOF", output: "EVIDENCE SEQUENCE", checkpoint: "Does every important claim have the right proof standard?" },
    { label: "Build", title: "Turn the argument into a fast, accessible page.", copy: "Copy, hierarchy, interaction, responsive behaviour, forms, analytics, and technical QA ship as one live-ready system.", input: "ARGUMENT + EVIDENCE", output: "LIVE-READY PAGE", checkpoint: "Can every visitor read, act, and recover on any device?" },
    { label: "Learn", title: "Read behaviour as a diagnosis, not a verdict.", copy: "Scroll depth, CTA paths, form quality, recordings, source mix, and pipeline outcomes identify the page layer worth changing next.", input: "BEHAVIOUR + LEAD QUALITY", output: "EXPERIMENT LEDGER", checkpoint: "Is the problem attention, comprehension, belief, friction, or fit?" },
  ],
  returnLabel: "PAGE BEHAVIOUR UPDATES THE ARGUMENT, NOT RANDOM DECORATION",
  assetHeading: "The page compounds when its argument becomes reusable.",
  assetLede: "A good page leaves behind more than code. It creates message modules, proof logic, behavioural evidence, and a tested path other campaigns can inherit.",
  assets: [
    { label: "SPINE", title: "Page argument map", copy: "Visitor intent, belief sequence, objection order, proof requirements, CTA contract, and exit paths." },
    { label: "MODULES", title: "Reusable proof system", copy: "Claims, testimonials, product evidence, process explanations, comparisons, and risk reducers with clear usage rules." },
    { label: "LEARNING", title: "Experiment ledger", copy: "Baseline, hypotheses, event meaning, test history, results, caveats, and the next safe change." },
  ],
  packageHeading: "Ship one complete page-learning loop in 30 days.",
  packageLede: "The first motion focuses on one valuable traffic path, one argument, one conversion action, and one measurement contract.",
  phases: [
    { period: "DAYS 01-05", title: "Diagnose the traffic contract", copy: "Audit source, audience, current page, message drift, proof, form friction, and technical constraints.", deliverables: "Intent map · friction diagnosis · baseline" },
    { period: "DAYS 06-12", title: "Write the argument spine", copy: "Define the belief sequence, proof plan, CTA contract, content hierarchy, and responsive wireframe.", deliverables: "Page argument · proof map · wireframe" },
    { period: "DAYS 13-21", title: "Design and build the system", copy: "Create the page in the existing brand language, connect forms and analytics, and test responsive and accessible behaviour.", deliverables: "Responsive page · instrumentation · QA record" },
    { period: "DAYS 22-30", title: "Launch and read the signal", copy: "Verify routing, observe early behaviour, review lead quality, and choose the first evidence-backed iteration.", deliverables: "Live page · signal review · experiment backlog" },
  ],
  studioOwns: ["Traffic and page diagnosis", "Argument, copy, and proof sequence", "Design and responsive implementation", "Analytics and interaction QA", "Initial learning review"],
  customerOwns: ["Traffic source and campaign context", "Approved product and customer proof", "Form destination and follow-up ownership", "Legal and brand approval", "Access to lead-quality feedback"],
  diagnosticHeading: "Find the exact point where your page stops earning the next action.",
  diagnosticCopy: "We review one page, its traffic source, message sequence, proof, CTA, form, and measurement. You get a one-page argument map showing the broken handoff and first layer worth rebuilding.",
  diagnosticIncludes: ["Intent-message mismatch", "Broken belief sequence", "Proof and objection gaps", "CTA and form friction", "First page experiment"],
  faqs: [
    { question: "Do you design and build the page?", answer: "Yes. The motion can include strategy, copy, interaction design, responsive implementation, analytics, and launch QA. We preserve a working stack unless a change has a clear commercial reason." },
    { question: "Can you improve an existing page instead?", answer: "Yes. If the page has usable traffic and a sound technical base, improving the argument or proof path may create more value than rebuilding it." },
    { question: "Do you guarantee conversion lift?", answer: "No. Conversion depends on traffic quality, offer, brand, proof, sales follow-up, seasonality, and sample size. We guarantee a clear hypothesis, sound implementation, and an honest learning process." },
    { question: "What happens after launch?", answer: "We read page behaviour alongside lead and pipeline quality. The next change follows the diagnosed constraint. It does not default to endless cosmetic testing." },
  ],
  closingKicker: "A PAGE SHOULD LEAVE THE NEXT VERSION SMARTER",
  closingHeading: "Build the argument, ship the page, keep the learning.",
};

export const outboundActivation: ServicePageContent = {
  number: "03",
  slug: "outbound-activation",
  name: "Outbound activation",
  systemName: "Signal-to-Conversation System",
  circuitVariant: "conversation",
  metaTitle: "Outbound Activation System | Grow & Close",
  metaDescription: "Connect account fit, timely signals, focused research, relevant messages, human approval, and sales learning into an outbound motion built for real conversations.",
  heroLead: "Turn account signals into",
  heroAccent: "relevant conversations.",
  heroLede: "We connect ICP decisions, account signals, focused research, message hypotheses, human-approved outreach, and sales feedback so outbound earns attention without becoming a volume game.",
  diagnosticName: "Outbound Signal Map",
  ctaLabel: "Get the outbound map",
  diagnosticHref: diagnosticHref("Outbound Signal Map", "What outbound motion is underperforming or not yet live?:"),
  outcomes: ["Tighter account fit", "A reason to reach out", "Relevant message paths", "Learning from replies"],
  problemHeading: "A list, sequence, and sending tool do not make an outbound motion.",
  problemLede: "Most programs automate before deciding what makes an account worth contacting, why this moment matters, or what the sales team should learn from the response.",
  problems: [
    { title: "ICP filters imitate strategy.", copy: "Industry, employee count, and title produce a large list, but not a defensible reason why these accounts should care about this problem now." },
    { title: "Personalisation adds facts, not relevance.", copy: "Messages mention a podcast, job post, or funding round without connecting that signal to a credible commercial tension." },
    { title: "Sequences ignore human judgement.", copy: "Automation keeps sending after context changes, a bad signal appears, or the account needs a different path. Volume hides the quality problem." },
    { title: "Replies vanish into the CRM.", copy: "Positive, negative, and ambiguous responses never update the signal model, message library, offer, or next account cohort." },
  ],
  symptom: "Activity rises while useful conversations stay flat",
  rootCause: "No operating link between account fit, timing, message relevance, human review, and sales learning",
  circuitHeading: "Choose an outbound node. See what must be true before it fires.",
  circuitLede: "Outbound works when every contact has a fit reason, a timing reason, a message hypothesis, an approved action, and a learning path back into the next cohort.",
  stages: [
    { label: "Fit", title: "Define the account condition, not a giant market.", copy: "We translate ICP into observable company conditions, buying context, disqualifiers, stakeholder roles, and the problem the motion is allowed to pursue.", input: "ICP + COMMERCIAL PRIORITY", output: "ACCOUNT CONDITION", checkpoint: "Why would this account plausibly have this problem?" },
    { label: "Signal", title: "Find a reason this moment may matter.", copy: "Product changes, hiring patterns, leadership moves, stack clues, public priorities, intent, and owned engagement become ranked triggers with confidence levels.", input: "ACCOUNT CONDITION + DATA", output: "PRIORITISED SIGNALS", checkpoint: "Does the signal change relevance or only decorate the email?" },
    { label: "Research", title: "Gather only the context the message needs.", copy: "Focused account and person research tests the hypothesis, removes false positives, and identifies the most credible entry point.", input: "PRIORITISED ACCOUNT", output: "RESEARCH BRIEF", checkpoint: "What evidence would make us bail out?" },
    { label: "Message", title: "Write for a response, not a completed sequence.", copy: "The message connects observable context to a specific tension, useful point of view, proof, and low-friction next step. Human approval stays in the loop.", input: "RESEARCH + MESSAGE SYSTEM", output: "APPROVED OUTREACH", checkpoint: "Would a reasonable buyer understand why them, why now, and why reply?" },
    { label: "Learn", title: "Route response into sales and the next cohort.", copy: "Replies, silence, objections, bad-fit signals, meetings, and pipeline quality update account rules, triggers, messages, and handoffs.", input: "RESPONSE + SALES OUTCOME", output: "COHORT LEARNING", checkpoint: "Was the failure fit, timing, relevance, trust, or offer?" },
  ],
  returnLabel: "REPLIES AND SALES OUTCOMES UPDATE THE NEXT ACCOUNT COHORT",
  assetHeading: "The asset is not a sequence. It is a better signal model.",
  assetLede: "Every outbound cycle should leave the team better at choosing accounts, reading timing, framing relevance, and handing real interest to sales.",
  assets: [
    { label: "FIT", title: "Account condition model", copy: "Observable fit conditions, disqualifiers, stakeholder roles, trigger families, and confidence rules." },
    { label: "MESSAGE", title: "Signal-led message library", copy: "Approved hypotheses, research prompts, message paths, proof modules, reply branches, and stop conditions." },
    { label: "LEARNING", title: "Conversation ledger", copy: "Replies, objections, bad-fit evidence, meeting quality, sales notes, and cohort-level decisions." },
  ],
  packageHeading: "Launch one bounded signal-to-conversation motion.",
  packageLede: "The first month focuses on one account condition, a small set of defensible signals, one stakeholder path, and a feedback loop sales can actually use.",
  phases: [
    { period: "DAYS 01-07", title: "Choose the account condition", copy: "Align the commercial priority, ICP evidence, disqualifiers, stakeholder, trigger families, and handoff expectations.", deliverables: "Account condition · disqualifiers · signal shortlist" },
    { period: "DAYS 08-14", title: "Build and verify the cohort", copy: "Source a controlled account set, verify signal quality, run focused research, and remove weak or misleading triggers.", deliverables: "Verified cohort · research briefs · confidence rules" },
    { period: "DAYS 15-21", title: "Create the message paths", copy: "Write primary and reply messages, connect proof, define human review, and prepare sales context for qualified responses.", deliverables: "Message library · approval rules · handoff brief" },
    { period: "DAYS 22-30", title: "Activate and learn", copy: "Launch the bounded cohort, monitor replies and stops, review with sales, and update fit, signal, and message decisions.", deliverables: "Live cohort · response ledger · next-cohort decision" },
  ],
  studioOwns: ["Account and signal strategy", "Research workflow and cohort QA", "Message hypotheses and reply paths", "Human approval and stop rules", "Response and learning review"],
  customerOwns: ["Commercial priority and ICP access", "CRM, data, and sending permissions", "Approved proof and claims", "Sales ownership of live conversations", "Compliance and deliverability requirements"],
  diagnosticHeading: "Find where your outbound loses fit, timing, relevance, or trust.",
  diagnosticCopy: "We review one active or proposed motion: account rules, data, signals, research, messages, handoff, and reply learning. You get a one-page map of the broken logic and smallest cohort worth testing.",
  diagnosticIncludes: ["ICP and disqualifier gaps", "Weak or decorative signals", "Research waste", "Message and proof friction", "First bounded cohort"],
  faqs: [
    { question: "Do you send the outreach?", answer: "The motion can include workflow setup, list QA, copy, staging, and monitored activation. Publishing and sending permissions remain explicit. Sales owns live buyer conversations." },
    { question: "Do you use automated personalisation?", answer: "Automation can gather and structure public context. It cannot decide relevance, invent a trigger, or approve a message. High-risk or weak-confidence accounts stop for human review." },
    { question: "How many contacts do you send to?", answer: "Volume follows evidence, not a preset quota. We start with a cohort large enough to learn but small enough to inspect. A weak signal does not deserve more sends." },
    { question: "What counts as success?", answer: "Useful replies, qualified conversations, sales acceptance, opportunity quality, and better account decisions. Opens and sends are operational checks, not the commercial outcome." },
  ],
  closingKicker: "RELEVANCE BEFORE VOLUME",
  closingHeading: "Build outbound that learns why buyers respond.",
};

export const aeoAndDataStories: ServicePageContent = {
  number: "05",
  slug: "aeo-and-data-stories",
  name: "AEO & data stories",
  systemName: "Citation Engine",
  circuitVariant: "citation",
  metaTitle: "AEO & Data Story System | Grow & Close",
  metaDescription: "Map high-value buyer questions, assemble defensible evidence, publish citation-ready answers, and monitor where your expertise appears across search and AI discovery.",
  heroLead: "Own the answer buyers",
  heroAccent: "ask AI to find.",
  heroLede: "We connect buyer questions, original evidence, expert judgement, answer structure, technical discoverability, distribution, and citation monitoring into a defensible answer-ownership system.",
  diagnosticName: "Answer-Ownership Map",
  ctaLabel: "Get the answer map",
  diagnosticHref: diagnosticHref("Answer-Ownership Map", "Which category or buyer questions should your company credibly own?:"),
  outcomes: ["Questions worth owning", "Evidence behind answers", "Citation-ready publishing", "Discovery signals"],
  problemHeading: "Publishing more content does not make your company the answer.",
  problemLede: "Search and AI systems reward clear entities, useful answers, corroborated evidence, and accessible structure. Generic volume creates pages. It rarely creates authority worth retrieving.",
  problems: [
    { title: "Topics replace buyer questions.", copy: "The calendar targets broad keywords while the real evaluation questions, comparisons, definitions, and decision criteria stay unanswered." },
    { title: "Claims have no evidence path.", copy: "Articles repeat category consensus, cite secondary summaries, or publish numbers without methodology, provenance, caveats, or a stable source." },
    { title: "Expertise is trapped in people and files.", copy: "Customer patterns, operator judgement, product data, and internal research never become structured, crawlable, reusable public evidence." },
    { title: "Visibility is measured without attribution quality.", copy: "Rankings and mentions look positive, but nobody checks which query, answer passage, source, or downstream buyer action created value." },
  ],
  symptom: "Your company publishes but rarely becomes the referenced source",
  rootCause: "No governed link between buyer questions, defensible evidence, answer structure, discoverability, and citation learning",
  circuitHeading: "Select an evidence node. See how it becomes an answer worth citing.",
  circuitLede: "Answer ownership compounds when original evidence and expert judgement become structured public sources, then discovery signals reveal which questions and passages deserve deeper authority.",
  stages: [
    { label: "Question", title: "Map the questions that shape a buying decision.", copy: "We connect search demand, sales calls, community language, support patterns, competitor gaps, and AI answer surfaces into a prioritised question universe.", input: "BUYER + DISCOVERY SIGNALS", output: "QUESTION OWNERSHIP MAP", checkpoint: "Would owning this answer change trust or a buying decision?" },
    { label: "Evidence", title: "Build the source before writing the answer.", copy: "Product data, expert interviews, customer patterns, public datasets, tests, and cited primary sources become a provenance-aware evidence pack.", input: "PRIORITY QUESTION", output: "EVIDENCE PACK", checkpoint: "Can another person inspect how this claim was produced?" },
    { label: "Answer", title: "Make the useful passage easy to retrieve.", copy: "Definitions, direct answers, supporting detail, tables, limitations, methodology, entities, and structured data form a clear source for people and machines.", input: "EVIDENCE + EXPERT JUDGEMENT", output: "CITATION-READY STORY", checkpoint: "Does the answer stand alone without hiding its caveats?" },
    { label: "Distribute", title: "Create corroboration without duplicating noise.", copy: "Owned pages, data stories, expert commentary, partner references, social explanations, and sales reuse point back to stable source material.", input: "PUBLISHED SOURCE", output: "DISCOVERY FOOTPRINT", checkpoint: "Does each channel add context or merely repeat text?" },
    { label: "Monitor", title: "Track answer quality, citation, and buyer response.", copy: "Search performance, AI mentions, cited passages, referral paths, branded demand, sales usage, and content gaps update the next evidence investment.", input: "DISCOVERY + COMMERCIAL SIGNALS", output: "ANSWER LEARNING LEDGER", checkpoint: "Are we visible, correctly represented, and commercially useful?" },
  ],
  returnLabel: "DISCOVERY GAPS DETERMINE THE NEXT QUESTION AND EVIDENCE INVESTMENT",
  assetHeading: "Authority compounds through inspectable source material.",
  assetLede: "The durable advantage is a growing library of questions, evidence, methodologies, entities, and answer passages that other people and systems can verify.",
  assets: [
    { label: "MAP", title: "Answer-ownership graph", copy: "Buyer questions, journey stage, current answer quality, source gaps, entity relationships, and commercial value." },
    { label: "SOURCE", title: "Evidence and methodology library", copy: "Primary sources, internal data definitions, expert notes, calculations, caveats, provenance, and reusable tables." },
    { label: "SIGNAL", title: "Citation learning ledger", copy: "Queries, cited passages, answer accuracy, referring sources, branded demand, sales usage, and next content decision." },
  ],
  packageHeading: "Own one high-value answer cluster before chasing the whole category.",
  packageLede: "The first month maps a bounded question space, closes the evidence gap, publishes one flagship source and supporting answers, then establishes monitoring.",
  phases: [
    { period: "DAYS 01-07", title: "Map the answer opportunity", copy: "Audit buyer questions, search and AI surfaces, existing pages, entities, competitor sources, sales language, and evidence gaps.", deliverables: "Question graph · visibility baseline · source-gap map" },
    { period: "DAYS 08-14", title: "Assemble defensible evidence", copy: "Collect primary sources, interview experts, define data and methodology, verify claims, and document limitations.", deliverables: "Evidence pack · methodology · claim register" },
    { period: "DAYS 15-23", title: "Publish the answer system", copy: "Create the flagship data story or guide, supporting direct answers, structured markup, internal links, and reusable expert passages.", deliverables: "Flagship source · answer cluster · structured data" },
    { period: "DAYS 24-30", title: "Distribute and monitor", copy: "Activate expert, partner, social, sales, and owned paths. Record citation, representation, referral, and buyer signals.", deliverables: "Distribution plan · monitoring view · next evidence bet" },
  ],
  studioOwns: ["Question and answer-surface research", "Evidence synthesis and source governance", "Data-story narrative and production", "Technical answer structure and schema", "Citation and commercial monitoring plan"],
  customerOwns: ["Expert and data access", "Accuracy review and source approval", "Permissions for customer or proprietary evidence", "Technical publishing access", "Clear boundaries for confidential information"],
  diagnosticHeading: "Find the valuable questions your current evidence cannot yet own.",
  diagnosticCopy: "We review one topic cluster across buyer questions, existing answers, search and AI surfaces, evidence, entities, and technical structure. You get a one-page map of the authority gap and first source worth building.",
  diagnosticIncludes: ["High-value question cluster", "Current answer and citation gap", "Evidence and provenance risk", "Entity and structure issues", "First flagship source"],
  faqs: [
    { question: "Can you guarantee AI citations?", answer: "No. AI systems change, personalise, and choose sources independently. We build clear, accurate, accessible, corroborated source material and monitor representation. We do not promise control over a model's answer." },
    { question: "Is AEO different from SEO?", answer: "The disciplines overlap. Technical access, search demand, authority, links, and useful pages still matter. AEO adds focus on answer passages, entities, evidence, corroboration, and how AI systems retrieve and represent sources." },
    { question: "Do we need proprietary data?", answer: "Not always. Original analysis can come from product patterns, expert synthesis, transparent tests, customer research, or well-structured public data. The source must still be useful, accurate, and inspectable." },
    { question: "What do you measure?", answer: "Question coverage, ranking and citation presence, answer accuracy, cited passages, referral quality, branded demand, sales reuse, and downstream actions. Mentions alone are not enough." },
  ],
  closingKicker: "PUBLISH SOURCES, NOT SEARCH FODDER",
  closingHeading: "Build the evidence your market can retrieve and trust.",
};

export const salesEnablement: ServicePageContent = {
  number: "06",
  slug: "sales-enablement",
  name: "Sales enablement",
  systemName: "Deal Momentum System",
  circuitVariant: "deal",
  metaTitle: "Sales Enablement System | Grow & Close",
  metaDescription: "Turn live-deal friction, one commercial story, modular proof, rep activation, and outcome learning into a sales enablement system that helps deals move.",
  heroLead: "Help every live deal move",
  heroAccent: "with one sharp story.",
  heroLede: "We connect deal friction, buyer questions, message architecture, modular proof, rep workflow, coaching, and outcome learning so enablement shows up inside the conversation, not in a forgotten content library.",
  diagnosticName: "Deal Friction Map",
  ctaLabel: "Get the friction map",
  diagnosticHref: diagnosticHref("Deal Friction Map", "Where do your live deals lose momentum?:"),
  outcomes: ["One deal narrative", "Proof by buying stage", "Assets reps can find", "Friction that updates them"],
  problemHeading: "Sales does not need more collateral. It needs less reinvention inside live deals.",
  problemLede: "The visible backlog is decks, one-pagers, and battlecards. The costly problem is that buyer questions, rep judgement, message, proof, and deal outcomes never become one operating loop.",
  problems: [
    { title: "Every rep rebuilds the story.", copy: "Good sellers adapt, but without a stable narrative they also improvise category, value, proof, and differentiation in ways the market cannot consistently remember." },
    { title: "Assets follow format, not deal friction.", copy: "The library is organised by file type while reps search by a buyer's objection, stakeholder, stage, competitor, or next meeting." },
    { title: "Proof is generic or hard to use.", copy: "Case studies tell a complete story, but live deals need the right excerpt, metric, implementation detail, or risk answer at the exact moment doubt appears." },
    { title: "Win-loss learning stays anecdotal.", copy: "Calls and CRM fields capture activity, but not which narrative, question, proof, or missing asset changed deal momentum." },
  ],
  symptom: "Reps keep requesting assets while rebuilding the pitch themselves",
  rootCause: "No deal-level link between buyer friction, narrative, proof, rep workflow, and outcome learning",
  circuitHeading: "Choose a deal node. See what the rep needs to move it forward.",
  circuitLede: "Enablement works when real buyer friction triggers the right narrative and proof, reps can use it in context, and deal outcomes update what the team teaches next.",
  stages: [
    { label: "Listen", title: "Capture friction from live buyer conversations.", copy: "Call notes, recordings, CRM context, rep requests, objections, stakeholder concerns, and lost-deal patterns enter a structured friction ledger.", input: "CALLS + DEAL CONTEXT", output: "FRICTION LEDGER", checkpoint: "Is this a repeated buying barrier or one rep preference?" },
    { label: "Diagnose", title: "Identify what the buyer cannot yet believe or do.", copy: "We separate message gaps, proof gaps, stakeholder misalignment, competitive pressure, process uncertainty, and next-step friction.", input: "FRICTION LEDGER", output: "DEAL MOMENT DIAGNOSIS", checkpoint: "What must change for the deal to move?" },
    { label: "Equip", title: "Create the smallest useful asset for that moment.", copy: "Talk tracks, proof cards, discovery prompts, mutual plans, objection paths, demo narratives, and stakeholder briefs inherit one commercial story.", input: "DIAGNOSIS + MESSAGE SYSTEM", output: "MODULAR DEAL ASSET", checkpoint: "Can a rep use this during the next real conversation?" },
    { label: "Activate", title: "Put the asset inside the rep workflow.", copy: "Rollout, examples, coaching, call review, CRM or enablement placement, and manager reinforcement turn a file into repeatable behaviour.", input: "ASSET + LIVE DEAL", output: "REP ADOPTION", checkpoint: "Can reps find, understand, and adapt it without a meeting?" },
    { label: "Learn", title: "Read adoption and deal movement together.", copy: "Usage, call quality, buyer response, stage movement, win-loss notes, and rep feedback decide what to improve, retire, or build next.", input: "USAGE + DEAL OUTCOME", output: "ENABLEMENT PRIORITY", checkpoint: "Did the asset change behaviour, belief, or momentum?" },
  ],
  returnLabel: "LIVE DEAL FRICTION SETS THE NEXT ENABLEMENT PRIORITY",
  assetHeading: "The library should organise itself around buyer moments.",
  assetLede: "A durable system gives every rep one narrative, modular proof, clear adaptation rules, and an evidence-backed reason for what gets built next.",
  assets: [
    { label: "STORY", title: "Deal narrative system", copy: "Core commercial story, discovery logic, stakeholder framing, competitor position, objections, and claim boundaries." },
    { label: "MODULES", title: "Buyer-moment asset kit", copy: "Proof cards, talk tracks, briefs, plans, demo paths, follow-up modules, and usage guidance organised by friction." },
    { label: "SIGNAL", title: "Deal friction ledger", copy: "Repeated barriers, asset requests, adoption, call evidence, stage movement, outcomes, and next enablement decisions." },
  ],
  packageHeading: "Fix one repeated deal barrier before expanding the library.",
  packageLede: "The first month follows one high-cost friction from calls to diagnosis, asset, activation, and outcome review.",
  phases: [
    { period: "DAYS 01-07", title: "Map the deal friction", copy: "Review calls, CRM notes, assets, rep requests, buyer questions, and recent wins or losses around one commercial priority.", deliverables: "Friction map · narrative drift audit · asset-gap priority" },
    { period: "DAYS 08-14", title: "Resolve the story and proof", copy: "Align the commercial narrative, proof standard, stakeholder path, objection logic, and adaptation boundaries.", deliverables: "Deal narrative · proof map · usage rules" },
    { period: "DAYS 15-21", title: "Build the buyer-moment kit", copy: "Create the minimum set of talk tracks, proof modules, briefs, plans, or follow-ups needed for the target moment.", deliverables: "Live-ready asset kit · examples · source files" },
    { period: "DAYS 22-30", title: "Activate and review", copy: "Launch with reps and managers, place assets in workflow, review calls, and record adoption and early deal response.", deliverables: "Rollout · coaching notes · friction ledger" },
  ],
  studioOwns: ["Call and deal-friction analysis", "Narrative and proof architecture", "Modular asset strategy and production", "Rep activation and usage guidance", "Outcome and priority review"],
  customerOwns: ["Call, CRM, and rep access", "Sales leader sponsorship", "Accurate product and customer proof", "Rep participation in rollout", "Deal outcome and adoption visibility"],
  diagnosticHeading: "Find the repeated buyer question your reps keep solving from scratch.",
  diagnosticCopy: "We review a focused set of calls, current assets, rep requests, and deal outcomes. You get a one-page map of the friction, story or proof gap, and first buyer-moment asset worth building.",
  diagnosticIncludes: ["Repeated deal friction", "Narrative drift", "Missing or unusable proof", "Workflow and adoption gap", "First buyer-moment asset"],
  faqs: [
    { question: "Do you build decks and battlecards?", answer: "Yes, when a live deal moment requires them. Format follows friction. We do not start with a content quota or rebuild the whole library without evidence." },
    { question: "Will this replace our enablement platform?", answer: "No. We can organise and place assets inside your existing workflow. The system governs narrative, proof, usage, and learning; software remains an implementation choice." },
    { question: "How much sales-team time is needed?", answer: "We need access to calls, a small rep and manager working group, and focused review. The goal is to reduce future requests and reinvention, not create another recurring meeting." },
    { question: "How do you measure enablement?", answer: "We combine findability, adoption, rep behaviour, buyer response, manager observation, stage movement, and win-loss context. Downloads alone do not show deal impact." },
  ],
  closingKicker: "BUILD FOR THE NEXT BUYER MOMENT",
  closingHeading: "Turn live deal friction into a system every rep can use.",
};

export const campaignStrategy: ServicePageContent = {
  number: "07",
  slug: "campaign-strategy",
  name: "Campaign strategy",
  systemName: "Campaign Operating System",
  circuitVariant: "campaign",
  metaTitle: "Campaign Strategy System | Grow & Close",
  metaDescription: "Turn one commercial bet into a connected campaign across audience, message, channels, assets, activation, control rules, and pipeline learning.",
  heroLead: "Turn one commercial bet into",
  heroAccent: "a connected market motion.",
  heroLede: "We connect audience, trigger, message, offer, channel jobs, assets, activation, sales handoff, and control rules so the campaign behaves like one commercial system instead of simultaneous channel activity.",
  diagnosticName: "Campaign Architecture Map",
  ctaLabel: "Get the campaign map",
  diagnosticHref: diagnosticHref("Campaign Architecture Map", "Which launch, segment, or commercial priority needs a campaign?:"),
  outcomes: ["One campaign thesis", "A job for every channel", "Explicit control rules", "Pipeline learning"],
  problemHeading: "Campaigns break when channels receive a date but not a shared decision system.",
  problemLede: "The team launches ads, email, social, pages, webinars, and sales plays together. Each asset looks active. The buyer experiences fragments with no clear commercial progression.",
  problems: [
    { title: "The theme is not a commercial bet.", copy: "A slogan gives creative teams a topic, but not the audience condition, expensive problem, belief change, offer, or evidence the campaign must test." },
    { title: "Every channel repeats the same asset.", copy: "Email, paid, social, events, partners, and sales copy inherit identical language instead of performing distinct jobs in the buyer journey." },
    { title: "Launch day replaces an operating cadence.", copy: "The project plan ends when assets go live. No one defines daily checks, weekly decisions, stop conditions, or how sales response changes the motion." },
    { title: "Reporting arrives after the budget is spent.", copy: "Channel metrics are assembled into a post-mortem without showing which audience, message, proof, or handoff assumption failed." },
  ],
  symptom: "Many campaign assets ship but the market never feels one idea",
  rootCause: "No architecture connecting the commercial bet, channel jobs, activation triggers, control rules, and pipeline learning",
  circuitHeading: "Select a campaign control. See what it governs across channels.",
  circuitLede: "A campaign compounds when one commercial thesis assigns different jobs to each channel, explicit signals control the next action, and sales outcomes improve the next bet.",
  stages: [
    { label: "Bet", title: "State the commercial hypothesis in one sentence.", copy: "Audience condition, expensive problem, belief to change, differentiated mechanism, offer, evidence, and expected business response become one falsifiable campaign thesis.", input: "COMMERCIAL PRIORITY", output: "CAMPAIGN THESIS", checkpoint: "What evidence would prove this bet wrong?" },
    { label: "Audience", title: "Choose who should move and what triggers attention.", copy: "Segment, buying context, stakeholder roles, awareness, exclusions, owned audiences, account signals, and sales context define the reachable campaign audience.", input: "THESIS + MARKET EVIDENCE", output: "AUDIENCE + TRIGGER MAP", checkpoint: "Why would this group care during this window?" },
    { label: "Architecture", title: "Give every channel a distinct job.", copy: "Paid earns reach, social builds familiarity, content proves the point, email advances interest, partners transfer trust, and sales converts context into conversation.", input: "AUDIENCE + BUYER PATH", output: "CHANNEL JOBS + ASSET MAP", checkpoint: "What changes in the buyer after each touch?" },
    { label: "Activate", title: "Launch the sequence, handoffs, and operating cadence.", copy: "Pages, creative, messages, routing, tracking, sales context, owner, timing, approvals, and escalation paths become one coordinated motion.", input: "ARCHITECTURE + ASSETS", output: "LIVE CAMPAIGN MOTION", checkpoint: "Can every handoff happen without a private rescue?" },
    { label: "Control", title: "Use signals to continue, change, or stop.", copy: "Audience quality, engagement depth, conversion, conversations, pipeline, cost, and qualitative response trigger explicit operating decisions.", input: "MARKET + PIPELINE SIGNALS", output: "CAMPAIGN DECISION LEDGER", checkpoint: "Do we scale, revise, pause, or learn?" },
  ],
  returnLabel: "CAMPAIGN LEARNING SHAPES THE NEXT COMMERCIAL BET",
  assetHeading: "The campaign leaves behind an operating model, not a folder of launch assets.",
  assetLede: "A durable campaign system preserves the hypothesis, audience logic, channel jobs, reusable proof, handoffs, and decision history behind the work.",
  assets: [
    { label: "BET", title: "Campaign thesis and audience contract", copy: "Commercial hypothesis, segment, trigger, belief change, offer, proof, exclusions, and success definition." },
    { label: "SYSTEM", title: "Channel and asset architecture", copy: "Channel jobs, sequence, creative system, page path, email, sales activation, ownership, timing, and dependencies." },
    { label: "CONTROL", title: "Campaign decision ledger", copy: "Baseline, operating signals, thresholds, interventions, stop rules, outcomes, caveats, and next-bet learning." },
  ],
  packageHeading: "Build one campaign from commercial bet to operating control.",
  packageLede: "The first month resolves the thesis, audience, channel jobs, priority assets, activation path, and live decision cadence around one bounded motion.",
  phases: [
    { period: "DAYS 01-06", title: "Write the campaign thesis", copy: "Align the priority, audience condition, problem, message, offer, proof, business outcome, and what would invalidate the bet.", deliverables: "Campaign thesis · audience contract · baseline" },
    { period: "DAYS 07-13", title: "Design the campaign architecture", copy: "Map the buyer progression, channel jobs, assets, page path, sales handoff, measurement, owners, and dependencies.", deliverables: "Channel map · asset system · operating plan" },
    { period: "DAYS 14-23", title: "Produce the priority motion", copy: "Build the essential page, creative, email, social, enablement, tracking, and routing needed for a coherent launch.", deliverables: "Live-ready campaign kit · sales brief · QA record" },
    { period: "DAYS 24-30", title: "Activate the control room", copy: "Launch in stages, verify handoffs, read early quality, apply thresholds, and document the first continue, revise, or stop decision.", deliverables: "Live campaign · control cadence · decision ledger" },
  ],
  studioOwns: ["Campaign thesis and architecture", "Cross-channel message and asset system", "Priority production and orchestration", "Sales handoff and measurement design", "Operating reviews and control decisions"],
  customerOwns: ["Commercial priority and offer", "Budget, platforms, and permissions", "Customer and product proof", "Sales follow-up ownership", "Fast stakeholder approval"],
  diagnosticHeading: "Find where your campaign fragments before the buyer can follow it.",
  diagnosticCopy: "We review one planned or active campaign across thesis, audience, message, offer, channel jobs, assets, handoffs, and measurement. You get a one-page architecture map showing the broken connections and first motion worth fixing.",
  diagnosticIncludes: ["Commercial-thesis gap", "Audience and trigger drift", "Channel-role duplication", "Sales and routing handoffs", "First campaign control"],
  faqs: [
    { question: "Is this campaign planning or execution?", answer: "Both can sit inside one motion. Strategy without activation leaves orchestration with you. Execution without a thesis creates disconnected assets. Scope follows the commercial priority and capacity." },
    { question: "Which channels do you support?", answer: "We activate only the channels the buyer path needs. This can include owned content, email, paid social, search, partners, events, outbound, pages, and sales enablement. More channels are not automatically better." },
    { question: "Is media spend included?", answer: "No. Strategy, creative, audience logic, measurement, and operating support can be included. Platform spend and third-party production costs remain separate and explicit." },
    { question: "What if the campaign underperforms?", answer: "We use predefined signals to locate the failed assumption: audience, message, offer, proof, channel, friction, or follow-up. We revise or stop based on evidence instead of protecting the original plan." },
  ],
  closingKicker: "ONE BET, MANY CHANNEL JOBS, ONE LEARNING LOOP",
  closingHeading: "Build the campaign buyers experience as one coherent motion.",
};

export const gtmDashboards: ServicePageContent = {
  number: "08",
  slug: "gtm-dashboards",
  name: "GTM dashboards",
  systemName: "Decision Dashboard System",
  circuitVariant: "decision",
  metaTitle: "GTM Dashboard System | Grow & Close",
  metaDescription: "Turn business questions, governed metric definitions, connected data, diagnostic views, operating cadence, and decisions into a dashboard system people use.",
  heroLead: "Turn scattered metrics into",
  heroAccent: "the next clear decision.",
  heroLede: "We connect business questions, metric contracts, source quality, diagnostic views, narrative, owners, thresholds, and operating cadence so reporting ends in a decision, not another dashboard tour.",
  diagnosticName: "Measurement Gap Map",
  ctaLabel: "Get the measurement map",
  diagnosticHref: diagnosticHref("Measurement Gap Map", "Which GTM decision is your current reporting failing to support?:"),
  outcomes: ["Questions before charts", "Governed metric meaning", "Drivers behind movement", "Decision cadence"],
  problemHeading: "Most GTM dashboards answer what happened inside tools, not what the business should do next.",
  problemLede: "Data gets connected and visualised before the decision, owner, definition, threshold, or intervention is clear. The dashboard becomes technically correct and operationally optional.",
  problems: [
    { title: "Tools dictate the reporting model.", copy: "CRM, ad platforms, analytics, and product systems each supply their favourite metrics. The business question disappears between tabs." },
    { title: "Definitions drift quietly.", copy: "Pipeline, source, qualified, influenced, active, conversion, and velocity mean different things across teams, queries, and meetings." },
    { title: "Charts show movement without drivers.", copy: "Leaders see that a metric changed, but cannot segment the movement, test likely causes, or distinguish signal from data-quality failure." },
    { title: "The meeting ends without a state change.", copy: "Reporting consumes time, generates commentary, and produces no recorded owner, action, threshold, stop rule, or follow-up date." },
  ],
  symptom: "More reporting creates more interpretation work",
  rootCause: "No governed link between business question, metric definition, data quality, diagnosis, owner, and intervention",
  circuitHeading: "Select a decision node. See the contract that makes its metric useful.",
  circuitLede: "A dashboard becomes operational when every view starts with a decision, every metric has governed meaning, every change can be diagnosed, and every review records what happens next.",
  stages: [
    { label: "Question", title: "Start with the decision the team must make.", copy: "We define the decision, owner, cadence, possible interventions, time horizon, and evidence needed before selecting metrics or charts.", input: "BUSINESS PRIORITY", output: "DECISION CONTRACT", checkpoint: "What action could change after seeing this view?" },
    { label: "Define", title: "Give every metric one governed meaning.", copy: "Name, formula, grain, source, owner, filters, inclusion rules, exclusions, timezone, attribution, and known limitations become explicit.", input: "DECISION CONTRACT", output: "METRIC CONTRACTS", checkpoint: "Could two analysts calculate the same number?" },
    { label: "Connect", title: "Validate the data path before polishing the chart.", copy: "Source coverage, joins, freshness, identity, missingness, duplication, reconciliation, and quality alerts establish whether the view deserves trust.", input: "METRIC CONTRACT + SOURCES", output: "VALIDATED DATA MODEL", checkpoint: "Is the movement real or a pipeline defect?" },
    { label: "Diagnose", title: "Show the driver, not only the headline.", copy: "Trend, target, segment, cohort, stage, source, owner, and exception views help the team locate where movement began and which explanation survives inspection.", input: "VALIDATED METRICS", output: "DECISION VIEW", checkpoint: "Can the viewer move from change to plausible cause?" },
    { label: "Decide", title: "Turn review into an owned intervention.", copy: "Thresholds, notes, action, owner, due date, expected effect, stop condition, and follow-up state make the dashboard part of operating work.", input: "VIEW + TEAM CONTEXT", output: "DECISION LEDGER", checkpoint: "What changes now, who owns it, and when do we look again?" },
  ],
  returnLabel: "DECISION OUTCOMES UPDATE METRICS, THRESHOLDS, AND THE NEXT QUESTION",
  assetHeading: "The durable system is shared metric meaning plus decision history.",
  assetLede: "Charts change. A governed semantic layer, quality contract, diagnostic path, and record of interventions keep the business from reopening the same measurement debate.",
  assets: [
    { label: "MEANING", title: "Metric contract library", copy: "Definitions, formulas, grain, source, owner, filters, attribution, caveats, and validation checks." },
    { label: "VIEW", title: "Decision dashboard", copy: "Headline, target, trend, drivers, segments, quality status, thresholds, notes, and next-action context." },
    { label: "STATE", title: "Decision and intervention ledger", copy: "Question, observation, diagnosis, owner, action, expected effect, stop condition, result, and learning." },
  ],
  packageHeading: "Build one decision system before centralising every metric.",
  packageLede: "The first month chooses one recurring GTM decision, governs its measures, validates the data, builds the diagnostic view, and installs the review cadence.",
  phases: [
    { period: "DAYS 01-06", title: "Write the decision contract", copy: "Align the business question, owner, cadence, possible actions, current reporting, source systems, and trust gaps.", deliverables: "Decision contract · question tree · source map" },
    { period: "DAYS 07-14", title: "Govern and validate the metrics", copy: "Define the measures, inspect data quality, reconcile sources, document caveats, and establish freshness and quality checks.", deliverables: "Metric contracts · validation record · quality rules" },
    { period: "DAYS 15-23", title: "Build the diagnostic view", copy: "Create the headline and driver views, segments, targets, thresholds, annotations, and accessible explanations.", deliverables: "Decision dashboard · data notes · owner guidance" },
    { period: "DAYS 24-30", title: "Run the operating review", copy: "Use the dashboard in a real meeting, record a decision, test the handoff, and adjust measures or views based on observed use.", deliverables: "Review cadence · decision ledger · next-question backlog" },
  ],
  studioOwns: ["Decision and KPI design", "Metric contracts and source mapping", "Data-quality validation", "Dashboard design and implementation", "Operating cadence and decision ledger"],
  customerOwns: ["Source-system access", "Business owners and metric stewards", "Target and threshold decisions", "Data engineering support where required", "Ownership of resulting interventions"],
  diagnosticHeading: "Find why your reporting stops before the decision.",
  diagnosticCopy: "We review one recurring GTM decision across current metrics, definitions, sources, quality, views, meeting use, and ownership. You get a one-page map of the measurement gaps and first decision system worth building.",
  diagnosticIncludes: ["Missing decision contract", "Metric-definition drift", "Data-quality and source gaps", "Diagnostic-view weakness", "First operating decision"],
  faqs: [
    { question: "Which dashboard tool do you use?", answer: "We preserve a suitable existing stack when possible. The decision model, metric contracts, and operating cadence matter more than the BI logo. Tool choice follows data, access, cost, and user needs." },
    { question: "Do you clean or engineer the data?", answer: "We validate sources, definitions, joins, freshness, and reconciliation. Light transformation can sit inside scope. Larger warehouse or pipeline work is identified explicitly and may require your data team or a separate motion." },
    { question: "Can you build executive and channel dashboards?", answer: "Yes, but not as one giant view. Each audience gets the decisions, measures, drivers, and cadence it owns. Shared definitions connect them." },
    { question: "How do we prevent dashboard decay?", answer: "Every metric has an owner, source, quality check, and usage context. Reviews record decisions and stale views can be retired when they no longer support an active question." },
  ],
  closingKicker: "MEASUREMENT SHOULD CHANGE WHAT HAPPENS NEXT",
  closingHeading: "Build the dashboard your operating decisions can trust.",
};

export const customerAdvocacy: ServicePageContent = {
  number: "09",
  slug: "customer-advocacy",
  name: "Customer advocacy",
  systemName: "Customer Evidence System",
  circuitVariant: "evidence",
  metaTitle: "Customer Advocacy System | Grow & Close",
  metaDescription: "Turn customer outcomes, well-timed asks, explicit consent, verified evidence, channel routing, and closed feedback into proof that travels.",
  heroLead: "Turn customer outcomes into",
  heroAccent: "proof that travels.",
  heroLede: "We connect happy moments, customer context, well-timed asks, consent, evidence capture, story production, channel routing, recognition, and feedback recovery into a customer evidence system.",
  diagnosticName: "Customer Evidence Map",
  ctaLabel: "Get the evidence map",
  diagnosticHref: diagnosticHref("Customer Evidence Map", "Where does customer proof currently get lost?:"),
  outcomes: ["Happy moments detected", "The right ask at the right time", "Verified reusable proof", "Customers kept in the loop"],
  problemHeading: "Your best customer proof already exists. The system around it does not.",
  problemLede: "Wins appear in calls, support messages, product milestones, and private notes. Without timing, consent, capture, routing, recognition, and recovery rules, the evidence disappears or the ask damages trust.",
  problems: [
    { title: "Happy moments pass without a next step.", copy: "A customer shares a win, expands usage, hits a milestone, or praises the team. Nobody recognises the moment as an advocacy trigger." },
    { title: "Every customer receives the same ask.", copy: "A case study request ignores relationship, outcome maturity, effort, risk, preferred format, and whether a smaller act would feel more natural." },
    { title: "Proof loses provenance and permission.", copy: "Quotes, metrics, logos, screenshots, and stories move between teams without a stable record of source, verification, consent, expiry, or approved usage." },
    { title: "Negative feedback takes the wrong path.", copy: "A request reaches an unhappy customer, or useful criticism gets treated as a testimonial failure instead of a recovery and product-learning signal." },
  ],
  symptom: "Teams keep asking for case studies while customer wins vanish",
  rootCause: "No governed loop connecting customer moments, ask choice, consent, evidence, routing, recognition, and recovery",
  circuitHeading: "Select an advocacy node. See what protects trust before proof travels.",
  circuitLede: "Advocacy compounds when the system notices genuine value, chooses a proportionate ask, verifies and permissions the evidence, returns value to the customer, and routes criticism toward recovery.",
  stages: [
    { label: "Detect", title: "Recognise the moments that may deserve an ask.", copy: "Milestones, positive feedback, expansion, adoption, support resolution, event participation, referrals, and relationship context become reviewed advocacy triggers.", input: "CUSTOMER + PRODUCT SIGNALS", output: "HAPPY-MOMENT QUEUE", checkpoint: "Is this genuine value, and is the relationship ready?" },
    { label: "Choose", title: "Match the ask to the customer and moment.", copy: "Review, quote, referral, interview, reference call, community contribution, event, post, or case study becomes a graduated path, not one default request.", input: "MOMENT + CUSTOMER CONTEXT", output: "APPROPRIATE ASK", checkpoint: "Is the value exchange clear and the effort proportionate?" },
    { label: "Capture", title: "Verify the story and record consent.", copy: "Outcome, before-state, mechanism, evidence, caveats, attribution, logo, quote, approved channels, review owner, and expiry become governed customer evidence.", input: "CUSTOMER STORY + PROOF", output: "PERMISSIONED EVIDENCE", checkpoint: "Can the customer recognise and defend this claim?" },
    { label: "Route", title: "Put each proof unit where it removes doubt.", copy: "Page modules, sales proof, ads, social posts, newsletter stories, community, references, and product education receive the evidence suited to their buyer moment.", input: "PERMISSIONED EVIDENCE", output: "CHANNEL-SPECIFIC PROOF", checkpoint: "Does this use match the consent and customer context?" },
    { label: "Close", title: "Return value and route feedback responsibly.", copy: "Customers receive thanks, visibility, access, learning, or recognition. Negative feedback enters recovery. Usage and buyer response update the next advocacy path.", input: "PUBLISHED STORY + FEEDBACK", output: "RELATIONSHIP + EVIDENCE STATE", checkpoint: "Did this strengthen trust for the customer and the market?" },
  ],
  returnLabel: "CUSTOMER RESPONSE UPDATES TIMING, ASK, CONSENT, AND THE NEXT PROOF PATH",
  assetHeading: "The durable asset is permissioned evidence with relationship context.",
  assetLede: "A customer evidence system makes proof findable and usable without separating the story from consent, provenance, expiry, recognition, or recovery obligations.",
  assets: [
    { label: "TRIGGERS", title: "Happy-moment and ask model", copy: "Signal sources, relationship checks, ask ladder, exclusions, effort levels, value exchange, and stop conditions." },
    { label: "EVIDENCE", title: "Customer evidence ledger", copy: "Story, outcome, proof, source, verification, consent, attribution, channels, expiry, owner, and status." },
    { label: "ROUTING", title: "Proof deployment system", copy: "Reusable proof units mapped to pages, campaigns, ads, sales moments, content, community, and reference paths." },
  ],
  packageHeading: "Install one customer-evidence loop before requesting more stories.",
  packageLede: "The first month audits existing proof, defines triggers and asks, builds governance, activates a small customer cohort, and routes the first permissioned evidence into live GTM moments.",
  phases: [
    { period: "DAYS 01-07", title: "Audit moments, proof, and trust", copy: "Review customer journey, feedback sources, current asks, existing stories, consent state, reference burden, relationship risks, and GTM proof gaps.", deliverables: "Evidence inventory · journey moments · trust-risk map" },
    { period: "DAYS 08-14", title: "Design the advocacy paths", copy: "Define happy-moment triggers, ask ladder, value exchange, eligibility, exclusions, recovery path, consent, expiry, and ownership.", deliverables: "Trigger model · ask ladder · governance rules" },
    { period: "DAYS 15-23", title: "Capture the first evidence cohort", copy: "Select a small set of suitable customers, stage human-approved asks, run interviews or capture, verify claims, and secure channel-specific consent.", deliverables: "Customer briefs · permissioned stories · evidence ledger" },
    { period: "DAYS 24-30", title: "Route proof and close the loop", copy: "Deploy evidence into priority pages, sales, content, or campaigns. Thank customers, monitor response, and record recovery or next-ask state.", deliverables: "Proof modules · activation plan · relationship follow-up" },
  ],
  studioOwns: ["Journey, proof, and advocacy diagnosis", "Trigger, ask, and governance design", "Customer interview and story production", "Consent-aware proof routing", "Recognition, feedback, and learning loop"],
  customerOwns: ["Customer relationship ownership", "Access to feedback and product signals", "Human approval before every ask", "Claim verification and legal review", "Recovery response for negative feedback"],
  diagnosticHeading: "Find where customer value stops becoming trusted evidence.",
  diagnosticCopy: "We review your customer journey, feedback sources, asks, existing proof, consent, sales needs, and publishing paths. You get a one-page map of lost moments, trust risks, and the first advocacy loop worth installing.",
  diagnosticIncludes: ["Missed happy moments", "Ask and value-exchange gaps", "Consent and provenance risk", "Proof-routing gaps", "First customer cohort"],
  faqs: [
    { question: "Is this a case-study production service?", answer: "Case studies may be one output. The system also supports quotes, reviews, references, referrals, community, social stories, event participation, proof cards, and smaller acts matched to customer context." },
    { question: "Who contacts the customer?", answer: "The relationship owner approves timing and approach. Grow & Close can prepare and facilitate the ask, interview, and review workflow. No customer receives an automated or unapproved advocacy request." },
    { question: "How do you handle consent?", answer: "Consent records the exact quote, claim, attribution, logo, format, channel, owner, review state, and expiry where needed. Broader future use is not assumed from one approval." },
    { question: "What happens when feedback is negative?", answer: "The advocacy path stops. The issue routes to the customer owner for acknowledgement, recovery, and product or service follow-up. Criticism is a relationship and learning signal, not failed marketing inventory." },
  ],
  closingKicker: "CUSTOMER TRUST BEFORE CUSTOMER PROOF",
  closingHeading: "Build the evidence system customers are comfortable powering.",
};

export const servicePages = {
  [positioningAndMessaging.slug]: positioningAndMessaging,
  [landingPages.slug]: landingPages,
  [outboundActivation.slug]: outboundActivation,
  [aeoAndDataStories.slug]: aeoAndDataStories,
  [salesEnablement.slug]: salesEnablement,
  [campaignStrategy.slug]: campaignStrategy,
  [gtmDashboards.slug]: gtmDashboards,
  [customerAdvocacy.slug]: customerAdvocacy,
} as const;
