export const serviceOfferings = [
  {
    number: "01",
    slug: "positioning-and-messaging",
    title: "Positioning & messaging",
    description: "Make buyers understand why you, now.",
    href: "/#capability-positioning-and-messaging",
  },
  {
    number: "02",
    slug: "landing-pages",
    title: "Landing pages",
    description: "Turn one sharp story into qualified action.",
    href: "/#capability-landing-pages",
  },
  {
    number: "03",
    slug: "outbound-activation",
    title: "Outbound activation",
    description: "Create conversations from accounts that fit.",
    href: "/#capability-outbound-activation",
  },
  {
    number: "04",
    slug: "founder-led-content",
    title: "Founder-led content",
    description: "Compound founder insight into owned demand.",
    href: "/services/founder-led-content",
  },
  {
    number: "05",
    slug: "aeo-and-data-stories",
    title: "AEO & data stories",
    description: "Become the cited answer, then prove the point.",
    href: "/#capability-aeo-and-data-stories",
  },
  {
    number: "06",
    slug: "sales-enablement",
    title: "Sales enablement",
    description: "Help reps sell the story without rebuilding it.",
    href: "/#capability-sales-enablement",
  },
  {
    number: "07",
    slug: "campaign-strategy",
    title: "Campaign strategy",
    description: "Connect one commercial idea across channels.",
    href: "/#capability-campaign-strategy",
  },
  {
    number: "08",
    slug: "gtm-dashboards",
    title: "GTM dashboards",
    description: "See what moved, why, and what ships next.",
    href: "/#capability-gtm-dashboards",
  },
  {
    number: "09",
    slug: "customer-advocacy",
    title: "Customer advocacy",
    description: "Turn customer outcomes into proof that travels.",
    href: "/#capability-customer-advocacy",
  },
] as const;
